version: '3.4'

services:
  caddy:
    image: abiosoft/caddy:0.10.14
    volumes:
      - ./caddy/Caddyfile.dev:/etc/Caddyfile:cached
    ports:
      - 80:80
      - 443:443
    environment:
      - ACME_AGREE=true
    restart: always
    networks:
      - lords-network

  db:
    image: "mysql:5.5"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CLIENT_PASSWORD: ${MYSQL_CLIENT_PASSWORD}
      MYSQL_READER_PASSWORD: ${MYSQL_READER_PASSWORD}
    volumes:
      - ./database:/database:cached
    networks:
      - lords-network
  
  ws:
    container_name: ws
    build:
      context: ws
      dockerfile: Dockerfile
    command: bash -c "mix deps.get && mix phx.server"
    ports:
      - 4000
    environment:
      MIX_ENV: dev
      PORT: 4000
    volumes:
      - ./ws:/app:cached
      - ./log/ws:/var/log/ws/:cached
    networks:
      - lords-network
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LORDS_DOMAIN: ${LORDS_DOMAIN}
      REVISION: ${REVISION}
      MYSQL_CLIENT_PASSWORD: ${MYSQL_CLIENT_PASSWORD}
      MYSQL_READER_PASSWORD: ${MYSQL_READER_PASSWORD}
      VISIBILITY: internal
    ports:
      - 80
    volumes:
      - ./api:/var/www/html:cached
      - ./log/api:/var/log/apache2:cached
    networks:
      - lords-network

  ai:
    image: "java:8"
    ports:
      - "5600:5600"
    volumes:
      - ./deployment:/deployment:cached
      - ./ai:/ai:cached
      - ./log/ai:/tmp/log:cached
    command: bash -c "cd /deployment ; chmod 755 ./deploy_ai.sh ; ./deploy_ai.sh"
    networks:
      - lords-network
  
  ui:
    container_name: ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 80
    volumes:
      - ./ui:/usr/src/app:cached
      - ./api/static_js:/usr/src/app/src/lib/static_js
    command: npm run serve
    networks:
      - lords-network

networks:
  lords-network:
