version: '3.4'

services:
  db:
    image: "mysql:5.5"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CLIENT_PASSWORD: ${MYSQL_CLIENT_PASSWORD}
      MYSQL_READER_PASSWORD: ${MYSQL_READER_PASSWORD}
    volumes:
      - ./database:/database
    networks:
      - lords-network
  
  ws:
    build:
      context: ws
      dockerfile: Dockerfile
    command: bash -c "mix deps.get && mix phx.server"
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PORT: 4000
    volumes:
      - ./ws:/app
    networks:
      - lords-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      LORDS_DOMAIN: ${LORDS_DOMAIN}
      REVISION: ${REVISION}
      MYSQL_CLIENT_PASSWORD: ${MYSQL_CLIENT_PASSWORD}
      MYSQL_READER_PASSWORD: ${MYSQL_READER_PASSWORD}
    volumes:
      - ./web:/var/www/html
      - ./log:/var/log/apache2
    networks:
      - lords-network

  ai:
    image: "java:7"
    ports:
      - "5600:5600"
    volumes:
      - ./deployment:/deployment
      - ./ai:/ai
      - ./log:/tmp/log
    command: bash -c "cd /deployment ; chmod 755 ./deploy_ai.sh ; ./deploy_ai.sh"
    networks:
      - lords-network

networks:
  lords-network:
