- hosts: all
  gather_facts: yes

  vars:
    apache_packages:
      - libapache2-mod-php5
      #- libapache2-mod-proxy-http
    apache_mods_enabled:
      - proxy.load
      - proxy_http.load
      - rewrite.load
      - ssl.load
    apache_vhosts:
      - servername: "the-lords.org"
        documentroot: "/var/www/lords/web"
      - servername: "ape.the-lords.org"
        documentroot: "/var/www/lords/web"
        serveralias: "*.ape.the-lords.org"
        extra_parameters: |
              ProxyPass               /       http://localhost:6969/
              ProxyPassReverse        /       http://localhost:6969/
    apache_remove_default_vhost: true
    php_display_errors: "On"
    php_packages:
      - php5-mysql
      - php5-gd
    mysql_root_password: root

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php }
    - { role: geerlingguy.mysql }
    - { role: lords.database_init }
    - { role: achaussier.openjdk-jdk }
    - { role: achaussier.openjdk-jre }