---

galaxy_info:
  author: Alexandre Chaussier
  description: Install openjdk-jdk package
  company: Infopen (http://infopen.pro)
  license: MIT
  min_ansible_version: 1.5

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - utopic
        - vivid
    - name: Debian
      versions:
        - wheezy
        - jessie
  categories:
    - development
    - web

dependencies: []

