use lords;

DROP TABLE IF EXISTS `cards_i18n`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cards_i18n` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `card_id` int(10) unsigned NOT NULL,
  `language_id` int(10) unsigned NOT NULL,
  `name` varchar(50) NOT NULL,
  `description` varchar(1000),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`card_id`) REFERENCES `cards` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `cards_i18n` (language_id, `card_id`, name, description) VALUES
(2,1,'Телепорт',NULL),
(2,2,'Магическая башня',NULL),
(2,3,'Монетный двор',NULL),
(2,4,'Храм лечения',NULL),
(2,5,'Озеро',NULL),
(2,6,'Горы',NULL),
(2,7,'Копейщик',NULL),
(2,12,'Мечник',NULL),
(2,16,'Рыцарь',NULL),
(2,19,'Конный рыцарь',NULL),
(2,21,'Ниндзя',NULL),
(2,22,'Голем',NULL),
(2,23,'Таран',NULL),
(2,24,'Маг',NULL),
(2,25,'Некромант',NULL),
(2,26,'Дракон',NULL),
(2,27,'Огненный шар','Наносит 1 ед. урона с вероятностью 2/3.'),
(2,32,'Лечение','Восстанавливает 1 ед. здоровья или снимает паралич или бешенство. Восстанавливает 1 щит магу.'),
(2,36,'Молния','Сильная молния наносит 3 ед. урона с вероятностью 1/2. Слабая молния наносит 2 ед. урона с вероятностью 2/3.'),
(2,39,'Отделение души','С вероятностью 2/3 убивает юнит или 1/6 исцеляет или 1/6 повергает в бешенство.'),
(2,41,'Телепорт','Переместить любой юнит в свободную клетку.'),
(2,42,'Паралич','Парализует любой юнит.'),
(2,43,'Армагеддон','С вероятностью 2/3 уничтожает каждый объект на карте кроме замков'),
(2,44,'Метеоритный дождь','Наносит 2ед урона зданиям и юнитам. Площадь атаки 2 на 2.'),
(2,45,'Щит','+1 щит любому юниту.'),
(2,46,'Вред','С вероятностью 1/6: -60 золота любому игроку; убить любого юнита; разрушить любое здание; переместить юнитов в случайную зону; случайный игрок тянет у всех по карте; переместить чужое здание.'),
(2,47,'Контроль разума','С вероятностью 1/2 повергает юнит в бешенство или дает контроль над юнитом.'),
(2,48,'Русская рулетка','С вероятностью 1/6 убивает любого юнита.'),
(2,49,'Бешенство','Повергает выбранного юнита в бешенство.'),
(2,50,'Открыть карты выбранного игрока','1 раз открывает все карты выбранного игрока.'),
(2,51,'Телекинез','Вытянуть у любого игрока 1 карту.'),
(2,52,'Сокращение денег в два раза у всех игроков','Сокращает деньги в 2 раза у всех игроков.'),
(2,53,'Обеднение','-50 золота у выбраного игрока.'),
(2,54,'Обогащение','+50 золота.'),
(2,55,'Вампир','Призывает Вампира.'),
(2,56,'Ускорение','+2 хода выбранному юниту.'),
(2,57,'Рвение','С вероятностью 1/2 юнит ходит шахматным конем или +2 атаки юниту.'),
(2,58,'Польза','С вероятностью 1/6: починка всех своих зданий включая Замок; воскресить любого юнита; +60 золота; взять 2 карты; переместить всех юнитов из выбранной зоны; переместить и присвоить здание.'),
(2,59,'Улучшение','На выбор игрока +1 к атаке, здоровью и ходьбе; или с вероятностью 1/3 +3 к атаке, здоровью или ходьбе.'),
(2,60,'Починить здания','Починка всех своих здания включая Замок.'),
(2,61,'Телепорт',NULL),
(2,62,'Магическая башня',NULL),
(2,63,'Монетный двор',NULL),
(2,64,'Храм лечения',NULL),
(2,65,'Озеро',NULL),
(2,66,'Горы',NULL),
(2,67,'Копейщик',NULL),
(2,68,'Мечник',NULL),
(2,69,'Рыцарь',NULL),
(2,70,'Конный рыцарь',NULL),
(2,71,'Ниндзя',NULL),
(2,72,'Голем',NULL),
(2,73,'Таран',NULL),
(2,74,'Маг',NULL),
(2,75,'Некромант',NULL),
(2,76,'Дракон',NULL),
(2,77,'Огненный шар','Наносит 1 ед. урона с вероятностью 2/3.'),
(2,78,'Лечение','Восстанавливает 1 ед. здоровья или снимает паралич или бешенство. Восстанавливает 1 щит магу.'),
(2,79,'Молния','Сильная молния наносит 3 ед. урона с вероятностью 1/2. Слабая молния наносит 2 ед. урона с вероятностью 2/3.'),
(2,80,'Отделение души','С вероятностью 2/3 убивает юнит или 1/6 исцеляет или 1/6 повергает в бешенство.'),
(2,81,'Телепорт','Переместить любой юнит в свободную клетку.'),
(2,82,'Паралич','Парализует любой юнит.'),
(2,83,'Армагеддон','С вероятностью 2/3 уничтожает каждый объект на карте кроме замков'),
(2,84,'Метеоритный дождь','Наносит 2ед урона зданиям и юнитам. Площадь атаки 2 на 2.'),
(2,85,'Щит','+1 щит любому юниту.'),
(2,86,'Вред','С вероятностью 1/6: -60 золота любому игроку; убить любого юнита; разрушить любое здание; переместить юнитов в случайную зону; случайный игрок тянет у всех по карте; переместить чужое здание.'),
(2,87,'Контроль разума','С вероятностью 1/2 повергает юнит в бешенство или дает контроль над юнитом.'),
(2,88,'Русская рулетка','С вероятностью 1/6 убивает любого юнита.'),
(2,89,'Бешенство','Повергает выбранного юнита в бешенство.'),
(2,90,'Открыть карты выбранного игрока','1 раз открывает все карты выбранного игрока.'),
(2,91,'Телекинез','Вытянуть у любого игрока 1 карту.'),
(2,92,'Сокращение денег в два раза у всех игроков','Сокращает деньги в 2 раза у всех игроков.'),
(2,93,'Обеднение','-50 золота у выбраного игрока.'),
(2,94,'Обогащение','+50 золота.'),
(2,95,'Вампир','Призывает Вампира, который действует сам по себе - бьет ближайших юнитов и здания.'),
(2,96,'Ускорение','+2 хода выбранному юниту.'),
(2,97,'Рвение','С вероятностью 1/2 юнит ходит шахматным конем или +2 атаки юниту.'),
(2,98,'Польза','С вероятностью 1/6: починка всех своих зданий включая Замок; воскресить любого юнита; +60 золота; взять 2 карты; переместить всех юнитов из выбранной зоны; переместить и присвоить здание.'),
(2,99,'Улучшение','На выбор игрока +1 к атаке, здоровью и ходьбе; или с вероятностью 1/3 +3 к атаке, здоровью или ходьбе.'),
(2,100,'Починить здания','Починка всех своих здания включая Замок.'),
(2,101,'Лучник',NULL),
(2,102,'Арбалетчик',NULL),
(2,103,'Катапульта',NULL),
(2,104,'Казарма',NULL),
(2,105,'Стена',NULL);

INSERT INTO `cards_i18n` (language_id, `card_id`, name, description) VALUES
(1,1,'Portal',NULL),
(1,2,'Magic tower',NULL),
(1,3,'Coin factory',NULL),
(1,4,'Healing temple',NULL),
(1,5,'Lake',NULL),
(1,6,'Mountains',NULL),
(1,7,'Spearman',NULL),
(1,12,'Swordsman',NULL),
(1,16,'Knight',NULL),
(1,19,'Cavalier',NULL),
(1,21,'Ninja',NULL),
(1,22,'Golem',NULL),
(1,23,'Ram',NULL),
(1,24,'Wizard',NULL),
(1,25,'Necromancer',NULL),
(1,26,'Dragon',NULL),
(1,27,'Fireball','Causes 1 damage to a chosen unit with probability 2/3'),
(1,32,'Healing','Restores 1 health to a chosen unit or removes madness/paralysis or restores wizard''s shield'),
(1,36,'Lightning','Causes 3 damage to units with probability 1/2 (strong lightning) or 2 damage with probability 2/3 (weak lightning)'),
(1,39,'Soul detachment','Kills a unit with probability 2/3 or makes mad with probability 1/6 or heals with probability 1/6'),
(1,41,'Teleportation','Move any unit to any free square'),
(1,42,'Paralysis','Paralyse any unit. Unit remains inactive until healed or attacked'),
(1,43,'Armageddon','Destroys each unit and building (except castles) with probability 2/3'),
(1,44,'Meteor shower','Causes 2 damage to units and buildings (except castles) in area 2 x 2 squares'),
(1,45,'Shield','Give a magical shield to any unit'),
(1,46,'Black dice','One of the following events randomly: -60 gold to a chosen player; kill a chosen unit; destroy a chosen building (except castles); teleport someone else''s building (except castles); move all units to a random zone; a random player steals a card from all other players'),
(1,47,'Mind control','Gives control over a chosen unit with probability 1/2 or makes it mad with probability 1/2'),
(1,48,'Russian roulette','Kills a unit with probability 1/6'),
(1,49,'Madness','Makes a chosen unit mad. Mad units move to and attack the closest unit'),
(1,50,'Reveal cards','Chosen player reveals cards'),
(1,51,'Telekinesis','Steal a random card from a chosen player'),
(1,52,'Crysis','All players loose half of their gold'),
(1,53,'Empty chest','-50 gold to a chosen player'),
(1,54,'Chest of gold','+50 gold'),
(1,55,'Vampire','Summon a vampire in your zone. Vampire attacks closest units and buildings'),
(1,56,'Acceleration','+2 movement points to any unit'),
(1,57,'Eagerness','+2 attack points to a chosen unit with probability 1/2 or unit starts to move as a chess knight with probability 1/2'),
(1,58,'White dice','One of the following events randomly: repair all your buildings including the castle; resurrect any unit (if there are any); +60 gold; pick 2 cards from the deck; move all units out of a chosen zone; steal someone else''s building and move it anywhere'),
(1,59,'Enhancement','Either +1 attack, +1 move, +1 health to a chosen unit (uniform enhancement) or +3 to a random parameter (random enhancement)'),
(1,60,'Repair','Repair all your buildings including the castle'),
(1,61,'Portal',NULL),
(1,62,'Magic tower',NULL),
(1,63,'Coin factory',NULL),
(1,64,'Healing temple',NULL),
(1,65,'Lake',NULL),
(1,66,'Mountains',NULL),
(1,67,'Spearman',NULL),
(1,68,'Swordsman',NULL),
(1,69,'Knight',NULL),
(1,70,'Cavalier',NULL),
(1,71,'Ninja',NULL),
(1,72,'Golem',NULL),
(1,73,'Ram',NULL),
(1,74,'Wizard',NULL),
(1,75,'Necromancer',NULL),
(1,76,'Dragon',NULL),
(1,77,'Fireball','Causes 1 damage to a chosen unit with probability 2/3'),
(1,78,'Healing','Restores 1 health to a chosen unit or removes madness/paralysis or restores wizard''s shield'),
(1,79,'Lightning','Causes 3 damage to units with probability 1/2 (strong lightning) or 2 damage with probability 2/3 (weak lightning)'),
(1,80,'Soul detachment','Kills a unit with probability 2/3 or makes mad with probability 1/6 or heals with probability 1/6'),
(1,81,'Teleportation','Move any unit to any free square'),
(1,82,'Paralysis','Paralyse any unit. Unit remains inactive until healed or attacked'),
(1,83,'Armageddon','Destroys each unit and building (except castles) with probability 2/3'),
(1,84,'Meteor shower','Causes 2 damage to units and buildings (except castles) in area 2 x 2 squares'),
(1,85,'Shield','Give a magical shield to any unit'),
(1,86,'Black dice','One of the following events randomly: -60 gold to a chosen player; kill a chosen unit; destroy a chosen building (except castles); teleport someone else''s building (except castles); move all units to a random zone; a random player steals a card from all other players'),
(1,87,'Mind control','Gives control over a chosen unit with probability 1/2 or makes it mad with probability 1/2'),
(1,88,'Russian roulette','Kills a unit with probability 1/6'),
(1,89,'Madness','Makes a chosen unit mad. Mad units move to and attack the closest unit'),
(1,90,'Reveal cards','Chosen player reveals cards'),
(1,91,'Telekinesis','Steal a random card from a chosen player'),
(1,92,'Crysis','All players loose half of their gold'),
(1,93,'Empty chest','-50 gold to a chosen player'),
(1,94,'Chest of gold','+50 gold'),
(1,95,'Vampire','Summon a vampire in your zone. Vampire attacks closest units and buildings'),
(1,96,'Acceleration','+2 movement points to any unit'),
(1,97,'Eagerness','+2 attack points to a chosen unit with probability 1/2 or unit starts to move as a chess knight with probability 1/2'),
(1,98,'White dice','One of the following events randomly: repair all your buildings including the castle; resurrect any unit (if there are any); +60 gold; pick 2 cards from the deck; move all units out of a chosen zone; steal someone else''s building and move it anywhere'),
(1,99,'Enhancement','Either +1 attack, +1 move, +1 health to a chosen unit (uniform enhancement) or +3 to a random parameter (random enhancement)'),
(1,100,'Repair','Repair all your buildings including the castle'),
(1,101,'Archer',NULL),
(1,102,'Marksman',NULL),
(1,103,'Catapult',NULL),
(1,104,'Barracks',NULL),
(1,105,'Wall',NULL);

